import type { Metadata } from 'next';
import { Geist, Geist_Mono } from 'next/font/google';

import './globals.css';

import { Suspense } from 'react';

import { getInitThemeScript } from '@/features/theme-toggle';
import { WelcomeBanner } from '@/features/welcome-banner';
import Providers from './providers';

const geistSans = Geist({
  variable: '--font-geist-sans',
  subsets: ['latin'],
});

const geistMono = Geist_Mono({
  variable: '--font-geist-mono',
  subsets: ['latin'],
});

export const metadata: Metadata = {
  title: 'Create Next-Blog',
  description: 'Generated by create next blog',
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" suppressHydrationWarning>
      <head>
        <script
          dangerouslySetInnerHTML={{
            __html: getInitThemeScript({
              storageKey: 'my-app-theme',
              defaultTheme: 'system', // или "light/dark"
              attribute: 'class',
              enableSystem: true,
            }),
          }}
        />
      </head>
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <Providers>
          <Suspense>
            <WelcomeBanner />
          </Suspense>
          {children}
        </Providers>
      </body>
    </html>
  );
}
